### ISSUE TITLE
RGB doesn't work with percentages. HSL/HSLA/HSV don't accept float values for SL/SV

### ISSUE THREAD

**Issue by indyarmy** [metaloha/color2color#1]
Working on it!

When this issue is fixed, things like "rgb(50%,200,0)" and "hsl(50%,0.45,25%)" wil be valid.

**Comment by metaloha** [comment]
This is finally updated in https://github.com/metaloha/color2color/pull/22 :) I believe all valid RGB[A] and HSL[A] formats shown on [MDN ](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) will work now!
