### ISSUE TITLE
Buy this domain

### ISSUE THREAD

**Issue by onlineth** [metaloha/color2color#7]
I don't want to buy indyarmy.com, I want to see a demo:)

![Imgur](http://i.imgur.com/o4YvANU.png)

**Comment by metaloha** [comment]
I'm impressed the ad-squatters actually got some valid search results for that domain :)

Thanks for noticing - I let the domain go a while ago, but haven't updated some of the repos for quite some time. There's no demo right now, but I'll put up some gh-pages soon to show it again.

**Comment by onlineth** [comment]
Great, thanks:)

**Comment by metaloha** [comment]
Demo up at http://metaloha.github.io/color2color/
