### ISSUE TITLE
HSLA being return with HSL

### ISSUE THREAD

**Issue by onlineth** [metaloha/color2color#8]
This is probably an easy fix but it looks like HSLA is being return only say HSL, here is an example:

``` javascript
color2color('#3fa796', 'HSLA')
> "hsl(170,45%,45%,1)"
```

It should return `hsla(170,45%,45%,1)`.

**Comment by metaloha** [comment]
Yup, looks like something good tests would catch :)

Now that I'm "back on the code wagon", so to speak, I'll be adding tests in the immediate-to-near future to catch things like this. Thanks!

**Comment by metaloha** [comment]
Screw it, snuck the fix into the current version :)

**Comment by onlineth** [comment]
Thanks:)
